<?php

declare(strict_types=1);

namespace Haakco\ParallelTestRunner\Reporting;

use Haakco\ParallelTestRunner\Data\ReportContext;
use Illuminate\Support\Facades\File;

final readonly class RuntimeBaselineWriter
{
    public function __construct(
        private ReportFormatter $formatter,
        private TrackingLoader $trackingLoader,
    ) {}

    public function write(ReportContext $context): void
    {
        $tracking = $this->trackingLoader->load($context->logDirectory);
        if ($tracking === null) {
            return;
        }

        $topSections = $this->trackingLoader->extractSectionMetrics($tracking, 100);
        $startedAt = $tracking['started_at'] ?? now()->toIso8601String();
        $duration = (float) ($tracking['duration'] ?? 0.0);

        $outputPath = $this->resolveOutputPath($context);
        File::ensureDirectoryExists(dirname($outputPath));

        $content = [];
        $content[] = '# Test Runtime Baselines';
        $content[] = '';
        $content[] = 'This file is auto-generated by the parallel test runner. Do not edit manually.';
        $content[] = '';
        $content[] = sprintf('_Last updated: %s_', $startedAt);
        $content[] = '';
        $content[] = sprintf('- Command: `%s`', $context->command);
        $content[] = sprintf('- Outcome: %s', $context->successful ? 'Passed' : 'Failed');
        $content[] = sprintf('- Log Directory: `%s`', $this->formatter->relativePath($context->logDirectory));
        $content[] = sprintf('- Total Runtime: %s', $this->formatter->formatDuration($duration));
        $content[] = '';
        $content[] = '| Section | Duration (s) | Tests | Assertions |';
        $content[] = '| --- | ---: | ---: | ---: |';

        if ($topSections === []) {
            $content[] = '| _No section data available_ | 0 | 0 | 0 |';
        } else {
            foreach ($topSections as $section) {
                $content[] = sprintf(
                    '| %s | %.2f | %d | %d |',
                    $section['name'],
                    $section['duration'],
                    $section['tests'],
                    $section['assertions'],
                );
            }
        }

        File::put($outputPath, implode(PHP_EOL, $content) . PHP_EOL);
    }

    private function resolveOutputPath(ReportContext $context): string
    {
        $configPath = config('parallel-test-runner.reports.runtime_baseline_path');
        if (is_string($configPath) && $configPath !== '') {
            return $configPath;
        }

        return rtrim($context->logDirectory, DIRECTORY_SEPARATOR) . '/runtime-baselines.md';
    }
}
