<?php

declare(strict_types=1);

namespace Haakco\ParallelTestRunner\Reporting;

use Haakco\ParallelTestRunner\Data\ReportContext;
use Illuminate\Support\Facades\File;

final readonly class SkipAuditWriter
{
    public function __construct(
        private ReportFormatter $formatter,
        private TrackingLoader $trackingLoader,
    ) {}

    public function write(ReportContext $context): void
    {
        $tracking = $this->trackingLoader->load($context->logDirectory);
        if ($tracking === null) {
            return;
        }

        $allSections = $this->trackingLoader->extractSectionMetrics($tracking, 1000);
        $startedAt = $tracking['started_at'] ?? now()->toIso8601String();

        $skippedSections = array_filter(
            $allSections,
            static fn(array $section): bool => $section['skipped'] > 0 || $section['incomplete'] > 0,
        );

        $outputPath = $this->resolveOutputPath($context);
        File::ensureDirectoryExists(dirname($outputPath));

        $content = [];
        $content[] = '# Test Skip / Flake Audit Snapshot';
        $content[] = '';
        $content[] = 'Auto-generated by the parallel test runner. Clear skips/incompletes before release.';
        $content[] = '';
        $content[] = sprintf('_Last updated: %s_', $startedAt);
        $content[] = '';

        if ($skippedSections === []) {
            $content[] = 'Latest run reported zero skipped or incomplete tests.';
        } else {
            $content[] = '| Section | Skipped | Incomplete |';
            $content[] = '| --- | ---: | ---: |';

            foreach ($skippedSections as $section) {
                $content[] = sprintf(
                    '| %s | %d | %d |',
                    $section['name'],
                    $section['skipped'],
                    $section['incomplete'],
                );
            }
        }

        $content[] = '';
        $content[] = sprintf('Source: `%s`', $this->formatter->relativePath($context->logDirectory));

        File::put($outputPath, implode(PHP_EOL, $content) . PHP_EOL);
    }

    private function resolveOutputPath(ReportContext $context): string
    {
        $configPath = config('parallel-test-runner.reports.skip_audit_path');
        if (is_string($configPath) && $configPath !== '') {
            return $configPath;
        }

        return rtrim($context->logDirectory, DIRECTORY_SEPARATOR) . '/skip-audit.md';
    }
}
